from christmastree import ChristmasTree
from time import sleep


tree = ChristmasTree()
tree.star.on()
leds = tree.leds

def all_leds(leds):
    for led in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]:
        leds[led].on()

def zero(leds):
    for led in [0]:
        leds[led].on()

def one(leds):
    for led in [1]:
        leds[led].on()
        
def two(leds):
    for led in [2]:
        leds[led].on()
        
def three(leds):
    for led in [3]:
        leds[led].on()
        
def four(leds):
    for led in [4]:
        leds[led].on()
        
def five(leds):
    for led in [5]:
        leds[led].on()
        
def six(leds):
    for led in [6]:
        leds[led].on()
                
def seven(leds):
    for led in [7]:
        leds[led].on()
                
def eight(leds):
    for led in [8]:
        leds[led].on()
                
def nine(leds):
    for led in [9]:
        leds[led].on()
        
        
def zero_b(leds):
    for led in [0, 1]:
        leds[led].on()

def one_b(leds):
    for led in [2, 3]:
        leds[led].on()
        
def two_b(leds):
    for led in [4, 5]:
        leds[led].on()
        
def three_b(leds):
    for led in [6, 7]:
        leds[led].on()
        
def four_b(leds):
    for led in [8, 9]:
        leds[led].on()

    

while True:
    #step 1 all on! 
    all_leds(leds)
    sleep(5)
    
    #step 2 up to down 300ms
    tree.baubles.off()
    sleep(.3)
    nine(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    eight(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    seven(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    six(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    five(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    four(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    three(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    two(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    one(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    zero(leds)
    sleep(.3)
    
    #step 2 down o up 300ms
    tree.baubles.off()
    sleep(.3)
    zero(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    one(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    two(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    three(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    four(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    five(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    six(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    seven(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    eight(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    nine(leds)
    sleep(.3)
    
    #step 3 up o down 200ms
    tree.baubles.off()
    sleep(.2)
    nine(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    eight(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    seven(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    six(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    five(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    four(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    three(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    two(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    one(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    zero(leds)
    sleep(.2)
    
    #step 4 down to up 200ms
    tree.baubles.off()
    sleep(.2)
    zero(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    one(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    two(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    three(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    four(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    five(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    six(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    seven(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    eight(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    nine(leds)
    sleep(.2)
    
    #step 5 up o down 100ms
    tree.baubles.off()
    sleep(.1)
    nine(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    eight(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    seven(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    six(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    five(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    four(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    three(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    two(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    one(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    zero(leds)
    sleep(.1)
    
    #step 5 down to up 100ms
    tree.baubles.off()
    sleep(.1)
    zero(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    one(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    two(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    three(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    four(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    five(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    six(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    seven(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    eight(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    nine(leds)
    sleep(.1)
    
    
    #step 6 BlinkBlinkBlink
    
    for i in range (33):
        tree.baubles.off()
        sleep(.5)
        all_leds(leds)
        sleep(.5)
        
        
    #step 7: down to up 300 ms (TwobyTwo)
    tree.baubles.off()
    sleep(.3)
    four_b(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    three_b(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    two_b(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    one_b(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    zero_b(leds)
    sleep(.3)
                
    #step 8: down to up 300 ms (TwobyTwo)
    tree.baubles.off()
    sleep(.3)
    zero_b(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    one_b(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    two_b(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    three_b(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    four_b(leds)
    sleep(.3)
    
    #step 9: down to up 200 ms (TwobyTwo)
    tree.baubles.off()
    sleep(.2)
    four_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    three_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    two_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    one_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    zero_b(leds)
    sleep(.2)
    
    #step 10: down to up 200 ms (TwobyTwo)
    tree.baubles.off()
    sleep(.2)
    zero_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    one_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    two_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    three_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    four_b(leds)
    sleep(.2)
    
    #step 11: down to up 100 ms (TwobyTwo)
    tree.baubles.off()
    sleep(.2)
    four_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    three_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    two_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    one_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    zero_b(leds)
    sleep(.2)
            
    #step 12: down to up 100 ms (TwobyTwo)
    tree.baubles.off()
    sleep(.2)
    zero_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    one_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    two_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    three_b(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    four_b(leds)
    sleep(.2)
    
    #step 13 BlinkBlinkBlink
    
    for i in range (33):
        tree.baubles.off()
        sleep(.5)
        all_leds(leds)
        sleep(.5)
        
    
    #Last Step... Have a Nice Sol Invictus!!!
        # by @JonnyBanana
        # https://github.com/JonnyBanana
    
    