from christmastree import ChristmasTree
from time import sleep



def zero(leds):
    for led in [0]:
        leds[led].on()

def one(leds):
    for led in [1]:
        leds[led].on()
        
def two(leds):
    for led in [2]:
        leds[led].on()
        
def three(leds):
    for led in [3]:
        leds[led].on()
        
def four(leds):
    for led in [4]:
        leds[led].on()
        
def five(leds):
    for led in [5]:
        leds[led].on()
        
def six(leds):
    for led in [6]:
        leds[led].on()
                
def seven(leds):
    for led in [7]:
        leds[led].on()
                
def eight(leds):
    for led in [8]:
        leds[led].on()
                
def nine(leds):
    for led in [9]:
        leds[led].on()

tree = ChristmasTree()
tree.star.off()
leds = tree.leds



while True:
                
    #step 1: down to up 300 ms
    tree.baubles.off()
    sleep(.3)
    zero(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    one(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    two(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    three(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    four(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    five(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    six(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    seven(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    eight(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    nine(leds)
    sleep(.3)
    # christmas star
    tree.star.on()
    sleep(.5)
    tree.star.off() 
    #step 2 up o down 300ms
    tree.baubles.off()
    sleep(.3)
    nine(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    eight(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    seven(leds)
    sleep(.3)  
    tree.baubles.off()
    sleep(.3)
    six(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    five(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    four(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    three(leds)
    sleep(.3)   
    tree.baubles.off()
    sleep(.3)
    two(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    one(leds)
    sleep(.3)
    tree.baubles.off()
    sleep(.3)
    zero(leds)
    sleep(.3)
    #step 3: down to up 200 ms
    tree.baubles.off()
    sleep(.2)
    zero(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    one(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    two(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    three(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    four(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    five(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    six(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    seven(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    eight(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    nine(leds)
    sleep(.2)
    # christmas star
    tree.star.on()
    sleep(.4)
    tree.star.off() 
    #step 4 up o down 200ms
    tree.baubles.off()
    sleep(.2)
    nine(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    eight(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    seven(leds)
    sleep(.2)  
    tree.baubles.off()
    sleep(.2)
    six(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    five(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    four(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    three(leds)
    sleep(.2)   
    tree.baubles.off()
    sleep(.2)
    two(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    one(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    zero(leds)
    sleep(.2)
    #step 5: down to up 100 ms
    tree.baubles.off()
    sleep(.1)
    zero(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    one(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    two(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    three(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    four(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    five(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    six(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    seven(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    eight(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    nine(leds)
    sleep(.1)
    # christmas star
    tree.star.on()
    sleep(.3)
    tree.star.off() 
    #step 6 up o down 100ms
    tree.baubles.off()
    sleep(.1)
    nine(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    eight(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    seven(leds)
    sleep(.1)  
    tree.baubles.off()
    sleep(.1)
    six(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    five(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    four(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    three(leds)
    sleep(.1)   
    tree.baubles.off()
    sleep(.1)
    two(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    one(leds)
    sleep(.1)
    tree.baubles.off()
    sleep(.1)
    zero(leds)
    sleep(.1)
    #step 7: down to up 200 ms
    tree.baubles.off()
    sleep(.2)
    zero(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    one(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    two(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    three(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    four(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    five(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    six(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    seven(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    eight(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    nine(leds)
    sleep(.2)
    # christmas star
    tree.star.on()
    sleep(.4)
    tree.star.off() 
    #step 8 up o down 200ms
    tree.baubles.off()
    sleep(.2)
    nine(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    eight(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    seven(leds)
    sleep(.2)  
    tree.baubles.off()
    sleep(.2)
    six(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    five(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    four(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    three(leds)
    sleep(.2)   
    tree.baubles.off()
    sleep(.2)
    two(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    one(leds)
    sleep(.2)
    tree.baubles.off()
    sleep(.2)
    zero(leds)
    sleep(.2)
    #restart the loop o 300ms